import { createContext } from 'react';

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    spaces: 'Parking Spaces',
    reports: 'Reports',
    payments: 'Payments',
    reservations: 'Reservations',
    pricing: 'Pricing',
    access: 'Access Control',
    settings: 'Settings',
    messaging: 'Messaging',
    logout: 'Log Out',
    welcome: 'Welcome back',
    totalSpaces: 'Total Spaces',
    occupied: 'Occupied',
    available: 'Available',
    revenue: 'Monthly Revenue',
    pending: 'Pending Payments',
    activeRes: 'Active Reservations',
    
    // Overview page translations
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    performanceOverview: 'Here is your parking performance overview',
    unavailable: 'Unavailable',
    reservationsCount: 'Reservations Count',
    noteTotal: 'Based on your capacity',
    noteAvailable: 'Ready for booking',
    noteOccupied: 'Currently in use',
    noteUnavailable: 'Disabled / Maintenance',
    noteRevenue: 'Actual stored data',
    noteReservations: 'Real reservations',
    occupancyTrend: 'Occupancy Trend',
    revenueTrend: 'Revenue Trend',
    noDataYet: 'No data yet',
    noRevenueDataYet: 'No revenue data yet',
    recentActivity: 'Recent Activity',
    noActivityYet: 'No activity yet',
    activityWillAppear: 'Activity will appear here once drivers start using your parking.',
    
    // Settings page translations
    settingsTitle: 'Settings',
    settingsDesc: 'Manage your account preferences',
    tabNotifications: 'Notifications',
    tabSecurity: 'Privacy & Security',
    tabLanguage: 'Language',
    tabHelp: 'Help & Support',
    displayLanguage: 'Display Language',
    selectLanguageDesc: 'Select your preferred language for the dashboard interface.',
    settingsSaved: 'Settings saved',
  },
  fr: {
    dashboard: 'Tableau de bord',
    spaces: 'Places de parking',
    reports: 'Rapports',
    payments: 'Paiements',
    reservations: 'Réservations',
    pricing: 'Tarification',
    access: "Contrôle d'accès",
    settings: 'Paramètres',
    messaging: 'Messagerie',
    logout: 'Se déconnecter',
    welcome: 'Bon retour',
    totalSpaces: 'Places totales',
    occupied: 'Occupées',
    available: 'Disponibles',
    revenue: 'Revenus mensuels',
    pending: 'Paiements en attente',
    activeRes: 'Réservations actives',
    
    // Overview page translations
    goodMorning: 'Bonsoir' /* In French 'Bonjour' is morning/afternoon */,
    goodAfternoon: 'Bon après-midi',
    goodEvening: 'Bonsoir',
    performanceOverview: 'Voici l\'aperçu des performances de votre parking',
    unavailable: 'Non disponibles',
    reservationsCount: 'Nombre de réservations',
    noteTotal: 'Basé sur votre capacité',
    noteAvailable: 'Prêt pour la réservation',
    noteOccupied: 'Actuellement utilisé',
    noteUnavailable: 'Désactivé / Entretien',
    noteRevenue: 'Données réelles stockées',
    noteReservations: 'Réservations réelles',
    occupancyTrend: "Tendance d'occupation",
    revenueTrend: 'Tendance des revenus',
    noDataYet: 'Pas encore de données',
    noRevenueDataYet: 'Pas encore de données de revenus',
    recentActivity: 'Activité récente',
    noActivityYet: 'Aucune activité pour le moment',
    activityWillAppear: "L'activité apparaîtra ici une fois que les conducteurs commenceront à utiliser votre parking.",
    
    // Settings page translations
    settingsTitle: 'Paramètres',
    settingsDesc: 'Gérez les préférences de votre compte',
    tabNotifications: 'Notifications',
    tabSecurity: 'Confidentialité & Sécurité',
    tabLanguage: 'Langue',
    tabHelp: 'Aide & Support',
    displayLanguage: "Langue d'affichage",
    selectLanguageDesc: 'Sélectionnez votre langue préférée pour l\'interface du tableau de bord.',
    settingsSaved: 'Paramètres enregistrés',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    spaces: 'أماكن الانتظار',
    reports: 'التقارير',
    payments: 'المدفوعات',
    reservations: 'الحجوزات',
    pricing: 'التسعير',
    access: 'التحكم في الوصول',
    settings: 'الإعدادات',
    messaging: 'الرسائل',
    logout: 'تسجيل الخروج',
    welcome: 'مرحباً بعودتك',
    totalSpaces: 'إجمالي الأماكن',
    occupied: 'مشغولة',
    available: 'متاحة',
    revenue: 'الإيرادات الشهرية',
    pending: 'مدفوعات معلقة',
    activeRes: 'الحجوزات النشطة',
    
    // Overview page translations
    goodMorning: 'صباح الخير',
    goodAfternoon: 'مساء الخير',
    goodEvening: 'مساء الخير',
    performanceOverview: 'هنا نظرة عامة على أداء موقف السيارات الخاص بك',
    unavailable: 'غير متاحة',
    reservationsCount: 'عدد الحجوزات',
    noteTotal: 'بناءً على السعة',
    noteAvailable: 'جاهز للحجز',
    noteOccupied: 'مشغول حالياً',
    noteUnavailable: 'معطل / صيانة',
    noteRevenue: 'البيانات الفعلية المخزنة',
    noteReservations: 'الحجوزات الحقيقية',
    occupancyTrend: 'اتجاه الإشغال',
    revenueTrend: 'اتجاه الإيرادات',
    noDataYet: 'لا توجد بيانات بعد',
    noRevenueDataYet: 'لا توجد بيانات إيرادات بعد',
    recentActivity: 'النشاط الأخير',
    noActivityYet: 'لا يوجد نشاط بعد',
    activityWillAppear: 'سوف يظهر النشاط هنا بمجرد أن يبدأ السائقون في استخدام موقف السيارات الخاص بك.',
    
    // Settings page translations
    settingsTitle: 'الإعدادات',
    settingsDesc: 'إدارة تفضيلات حسابك',
    tabNotifications: 'الإشعارات',
    tabSecurity: 'الخصوصية والأمان',
    tabLanguage: 'اللغة',
    tabHelp: 'المساعدة والدعم',
    displayLanguage: 'لغة العرض',
    selectLanguageDesc: 'اختر لغتك المفضلة لواجهة لوحة التحكم.',
    settingsSaved: 'تم حفظ الإعدادات',
  },
};

// French override for greeting context to make it natural
TRANSLATIONS.fr.goodMorning = 'Bonjour';

export const LangContext = createContext({
  t: TRANSLATIONS.en,
  lang: 'en',
  setLang: (_l: string) => {},
});
